name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install CMake
      run: brew install cmake

    - name: Build the Project
      run: make

    - name: Test
      run: make test
