name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: brew bundle

    - name: Import certificate
      env:
        APPLE_DEVELOPER_CERT: ${{ secrets.APPLE_DEVELOPER_CERT }}
        APPLE_DEVELOPER_CERT_PASSWORD: ${{ secrets. APPLE_DEVELOPER_CERT_PASSWORD }}
      run: |
        echo $APPLE_DEVELOPER_CERT | base64 --decode > cert.p12
        sudo security import cert.p12 -A -k /Library/Keychains/System.keychain -P "$APPLE_DEVELOPER_CERT_PASSWORD"
        rm cert.p12

    - name: Build the Project
      run: make

    - name: Test
      run: make test
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Developer Command Prompt (required for using nmake)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build with NMAKE
      run: |
        nmake
      shell: cmd

    - name: Test
      run: |
        nmake test
      shell: cmd
